// all the actions for the reducer

export const SIDEBAR_OPEN = 'SIDEBAR_OPEN'
export const SIDEBAR_CLOSE = 'SIDEBAR_CLOSE'

export const GET_PRODUCTS_START = 'GET_PRODUCTS_START'
export const GET_PRODUCTS = 'GET_PRODUCTS'
export const IS_PRODUCTS_ERROR = 'IS_PRODUCTS_ERROR'

export const MOBILE_FILTER_MENU_OPEN = 'MOBILE_FILTER_MENU_OPEN'
export const MOBILE_FILTER_MENU_CLOSE = 'MOBILE_FILTER_MENU_CLOSE'

export const UPDATE_CATEGORY_FILTERS = 'UPDATE_CATEGORY_FILTERS'
export const CATEGORY_FILTERS = 'CATEGORY_FILTERS'

export const UPDATE_SORT_FILTERS = 'UPDATE_SORT_FILTERS'
export const SORT_FILTERS = 'SORT_FILTERS'

export const SET_FILTERED_PRODUCTS = 'SET_FILTERED_PRODUCTS'

export const CLEAR_FILTERS = 'CLEAR_FILTERS'

export const GET_HIGHEST_PRICED_PRODUCT_AMT = 'GET_HIGHEST_PRICED_PRODUCT_AMT'
